### ISSUE TITLE
Migrate to Github Actions

### ISSUE THREAD

**Issue by streeve** [ECP-copa/Cabana#345]
Updates needed with the switch to GHA from Travis: 
- [x] Initial version (#325)
- [x] Add format (#351)
- [x] Clean up style (e.g. remove `cd build`) (#377)

GHA has shown that some distributions that fail (`fedora:latest` `fedora:intel` and `ubuntu:devel`)
- [x] Fix the `Cajita::Halo`

Features to implement in GHA:
- [x] HEFFTE FFTW build (#370)
- [x] HEFFTE MKL build (#370, disabled until fixed in heFFTe)
- [x] ARBORX build (#359)
- [x] Deploy doxygen (#396)
- [x] Enable ccache (#384)
- [x] HYPRE build (#385)

**Comment by junghans** [comment]
Thanks for writing this up.

**Comment by junghans** [comment]
We also need investigate why some tests fail on `fedora:latest` and `ubuntu:devel`.

**Comment by streeve** [comment]
All distributions are now passing - unsure why they originally failed and why they all started passing at the same time

**Comment by junghans** [comment]
All done.
