### ISSUE TITLE
Load balancing roadmap

### ISSUE THREAD

**Issue by streeve** [ECP-copa/Cabana#457]
Before we merge #444 I think we need to unify it with out existing capability now that Yuxing is back. I would suggest (feel free to edit):

- [ ] Create a base `LoadBalancer` class with the particle workload that exists in `SparseDimPartitioner`
- [ ] Inherit from `LoadBalancer` and overload a couple methods for the `SparseLoadBalancer` class
- [ ] Rename #444 `LoadBalancerALL` (or similar) and inherit from `LoadBalancer`

Maybe we need to discuss again what really belongs in the global grid vs partitioner vs load balancer, but the current steps may be enough

**Comment by streeve** [comment]
Draft in #541
